[gcp_service_account]
type = "service_account"
project_id = "kosofereferralapp"
private_key_id = "da578b1458c121326303401c0fb4c530b232e40a"

# >>>>> BEGIN CRITICAL SECTION FOR private_key <<<<<
# This must be a multi-line string.
# Ensure the "private_key = """ is on one line.
# Ensure the closing """ is on a completely new line by itself.
# The content between the triple quotes is copied EXACTLY from your credentials.json,
# including the BEGIN/END lines and all '\n' characters which will be treated as actual newlines by TOML.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCshiUYjv1b/LEI
Bnw5cjO0PaAhdzGO2Y+en3YNXbRXyZCI+ZBnH3AdBXSXOVbcXhk4EBKhy6I4DtQd
vWm0eosTUeYOPf/ifFWb90UGRMYEpjp+PUvXiGJcYHVRjlSr5Ok35BReRIgOb7tB
9qDS/CX5R9drz+6dzkao2KjrBOof3TsjpsRw8aqV7kV2uBRY9bHGc6bweKpEx89e
0MPY2B6Z7Ba90kf/WCBuk/ElJjpes1Ya32IsmV8hRsDL+xqZa+n8tkGwerDlSmkr
MboVE8Vr28tUXFzst0do5Lj7Jaf/Tx37VDNas6XAoFPROg1bOBWQBUXd0nExg6/X
Ok2MAfSLAgMBAAECggEAF+iwmWUE6EuY/m4Ppye+0fARvLGNClP3mwRUUuk1MKP8
G3oihfgNtyfmDtMLyOxi0v8p5dxCS0Ha1D2cuZNF/35ubcjafmO8ECpGGZFMXqE+
zUySByOdJgTZcrJROk/goOCYkLEvUyOEMFG321AbCcnn/nFJi1BmlchjgyEiOm9Z
sYHWrU3rCZ7fqXAlHf4TdaDajdAjHeXS8KazpFWjEqhaOledea6HZXNkRgRBgeFL
bP+SMPATcw7RqUHB9GIuRtb9rm3Cw3Pff/9X8Bcy8zTzNwl2oWL4Wni0dpytUOqm
659agsvNI/UfudK6GBR1UVBS8CPaUulGVZ2DbFlLMQKBgQDeWsLVXMduda5YZV8K
pY09ljtPrFy5Fqe6QzaDdw7IRjCWWGO87Gnntn8dcCRC9XOc+KwuXxkndo28aCN8
KDBDYLAG4QUBZvwqedwmCzu/x9uIQHq47OZBNRybMI46rEhZSc8Fq0ht8ZVezbtw
eJWlgKUHWmoImVTufz0J+I+54wKBgQDGoR91cxl0RvsHsf9+A3sNvQp1FmPKrSLB
XvDl8IjHR/6sZQqntmmjmALQaqCMWGFQHvMBuqCJW3RX/6oqsd7VIrOjQhA1WHFI
O5pzB3QZdClr3TCQJDA+8FbFQfxnIBWz0hsIjMTJkYNvfGIsxhzoGpEVnsrVHC6u
u/iv8ED7OQKBgBQnPcmA40KLwAWbCoY4gxi16SJLiQvtlb44IVTBEcHtOrIlyMRy
2RZ7YAIXC/JVtOjhURnS3MDK6gXNmonCSr2QoeO9uWprHyfqa523Hu8++hLbZUQl
lKkMW09lkz6WJuiQ3Aazg5kTcGprUzXaeBXMFykXdMzauOv09F9W/A/pAoGAM51O
1XBRXvvK45cHczFoWouTGhX1XIddDq6jHr1Abbhxn06qVCZ8kPxBTvNGQPH+Z5mD
QCHE8ayIMQ3IpEuQQgZAc94I5DPVTBXg7p8zNiIPWW4i3nHo75H4mk2pTwrxWMby
K2iZAmADrYa+5C+e91lf9iRLRNGL9+/0kZN271ECgYEAra/pY8cVVuXYk/NpJvNm
0zC1X3PvcZxuo3TD7AbsFbWNwjFmeJEzpGtx5rD5Gs1DKSvabGOoKOnz+vdUSLWa
4gyvxwkhoOmRxPBRs5KQpHBEOPkbwgmfYvgoN2ZTc4x2euANZvZrVD6hZHWC7bs2
6Qgj9iiY2unZn+t7hopUP8s=
-----END PRIVATE KEY-----
"""
# >>>>> END CRITICAL SECTION FOR private_key <<<<<

client_email = "streamlit-referral-app@kosofereferralapp.iam.gserviceaccount.com"
client_id = "112834310397118394712"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-referral-app%40kosofereferralapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"